export const surpriseMePrompts = [
    "A surrealist watercolor painting of a giraffe riding a unicycle on a tightrope above a waterfall.",
    "A digital collage artwork of a steampunk-inspired underwater world with clockwork sea creatures.",
    "An abstract sculpture made from recycled materials, representing the concept of 'harmony.'",
    "A mosaic-style mosaic artwork of a city skyline composed entirely of tiny, colorful butterflies.",
    "A surrealistic oil painting of a floating island in the shape of a giant teacup, surrounded by flying books.",
    "A three-dimensional diorama of a miniature post-apocalyptic cityscape with tiny scavenger robots.",
    "A whimsical clay sculpture of a wise owl wearing a top hat and monocle, perched on a stack of books.",
    "A kinetic art installation that uses wind to create mesmerizing patterns with sand and mirrors.",
    "An interactive light installation that responds to music and transforms into a dynamic visual symphony.",
    "A mixed media artwork combining photography and painting to depict a dreamy underwater library.",
    "A conceptual art piece featuring a suspended tree made entirely of glowing, bioluminescent resin.",
    "A 3D-printed sculpture of a futuristic city on the back of a giant mechanical turtle.",
    "A digital painting of a cybernetic jungle where mechanical plants intertwine with organic ones.",
    "A kinetic sculpture of a perpetually spinning top with miniature worlds inside each layer.",
    "A paper-cut artwork of a fantastical carnival with intricate details and hidden stories.",
    "A holographic installation that explores the concept of time travel through shifting dimensions.",
    "A digital artwork of an enchanted forest with trees that emit melodies when touched.",
    "An origami masterpiece of a mythical creature emerging from a folded paper sea.",
    "A mixed media artwork using shattered glass and mirrors to portray the shattered illusions of reality.",
    "A shadow puppet theater showcasing a whimsical story of a moon that fell in love with the sun.",
    "A kinetic art piece with pendulum-driven brushes that create ever-changing, intricate patterns.",
    "A sculpture made entirely of recycled computer parts, representing the fusion of nature and technology.",
    "A digital painting of a cosmic chess match played by planets and stars in a celestial arena.",
    "An interactive installation where visitors can manipulate light and sound to create their own art.",
    "A mosaic of colorful glass shards forming a phoenix rising from the ashes.",
    "A sculptural representation of a futuristic cityscape where buildings are shaped like musical instruments.",
    "A surrealistic oil painting of a library with floating books and staircases that defy gravity.",
    "A mixed media artwork combining real flowers with painted ones, blurring the line between reality and art.",
    "A kinetic sculpture of a never-ending staircase, inspired by the works of M.C. Escher.",
    "A digital painting of a city skyline with skyscrapers made of crystal and light, reflecting a utopian future.",
];  